### PR TITLE
feat: create JSON Browser tool

### PR DESCRIPTION
**Pull request by michaelfitzhavey**
At work I spend a lot of time investigating issues by browsing data to see which flag has been set to cause a certain set of conditions to happen. I.e. was `cropSlots: true` for a certain batch when printing from a certain file.

It would be really useful to have a tool where I can:
1. paste JSON in and view it formatted and nice (I found myself using json-formatter for this at work today)
2.  let sub objects be collapsed and hidden to make it more readable
3. search the JSON
4. compare against other JSON (although this sounds harder, maybe one for later)

Kind of like this: http://jsonviewer.stack.hu but way better 🥇 

**EDIT** _Oh shit we got http://json-browser.web.app_

### CODE REVIEW

**Comment by michaelfitzhavey** [comment]
## Todo: 
- [ ] make the tool
- [ ] add tool to the main website
- [ ] get reviews and ting
- [ ] deploy the tool

**Comment by michaelfitzhavey** [comment]
Deployed to firebase url here: https://json-browser.web.app, can I get a review?

**Comment by andrewlew1s** [comment]
Instead of 1 keys it should say 1 key

**Comment by michaelfitzhavey** [comment]
I've added a JSON Diff checker (comparison) tool to the roadmap in this PR as after some consideration I think it's different functionality to analysis, perhaps diff will extend the functionality of this app though.

Search is implemented in a basic form as `cmd+f` works, I think that's good enough for the MVP but would be good to improve later.

I like the idea of supporting linking our tools between each other, we'll need to support url queries to load the data from the link. I've added this to the roadmap.

> One thing I noticed was that instead of '1 keys' it should say '1 key'
No idea what you're referring to 🤔 

@andrewlew1s Can you approve or request any specific changes?

**Comment by michaelfitzhavey** [comment]
All deployed as @andrewlew1s didn't approve or request changes :(

**Pull request merged**
